#version: '2'
version: '3.2'
services:
 jekyll:
   build: ./cyberauftritt-git
   container_name: cyberauftritt_jekyll
   image: fsinf/cyberauftritt:latest
   command: bundle exec jekyll build --config /etc/deployment-config.yml,_config.yml
   volumes:
     - ./cyberauftritt-git:/srv/jekyll
     - ./deployment-config.yml:/etc/deployment-config.yml:ro
 nginx:
    image: fsinf/nginx:latest
    command: /usr/sbin/nginx -g 'daemon off;'
    container_name: cyberauftritt_nginx
    volumes:
      - ./cyberauftritt-git/_site:/srv/jekyll
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-hp.conf:/etc/nginx/sites-enabled/nginx-hp.conf:ro
      - /srv/docker/shared/nginx/security-headers.conf:/etc/nginx/shared/security-headers.conf:ro
      - /srv/docker/shared/nginx/ssl.conf:/etc/nginx/shared/ssl.conf:ro
    restart: always
    ports:
      - "192.168.134.60:8080:8080"
    depends_on:
      - jekyll
