version: '2'

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/data/nextcloud/data'
  database:
     driver: local
     driver_opts:
       type: 'none'
       o: 'bind'
       device: '/srv/data/nextcloud/database'

networks:
  backend:
     ipam:
       config:
         - subnet: 10.0.1.0/24
           gateway: 10.0.1.1


services:
  database:
    container_name: nextcloud_database
    image: postgres:12-alpine
    mem_limit: 1g         # version 2 only
    env_file:
      # another account for nextcloud is created, config can be found in the config.php in the config folder in nextcloud volume
      - .env_database
    volumes:
      - database:/var/lib/postgresql/data
    networks:
       backend:
         ipv4_address: 10.0.1.3
    restart: always
  app:
    container_name: nextcloud_container
    image: nextcloud:stable
    cpuset: 0,1,4,5
    mem_limit: 4g
    environment:
      - REDIS_HOST=redis
    volumes:
      - data:/var/www/html
    restart: always
    depends_on:
      - database
    networks:
      backend:
        ipv4_address: 10.0.1.2
  nginx:
    container_name: nextcloud_nginx
    image: fsinf/nginx:latest
    ports:
      - 8090:443
    volumes:
      - data:/var/www/html
      - /srv/docker-certificates/cloud.fsi.uni-tuebingen.de/:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-nextcloud.conf:/etc/nginx/sites-enabled/nginx-nextcloud.conf
      - /srv/docker/shared/nginx/ssl.conf:/etc/nginx/shared/ssl.conf:ro
      - /srv/docker/shared/nginx/security-headers.conf:/etc/nginx/shared/security-headers.conf:ro
    restart: always
    networks:
      backend:
        ipv4_address: 10.0.1.4
  redis:
    container_name: nextcloud_redis
    image: redis:latest
    mem_limit: 2g
    restart: always
    networks:
      backend:
        ipv4_address: 10.0.1.5
