version: '3.2'
services:
  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=hackmd
    volumes:
      - /srv/data/codimd/database:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 10.0.2.4
    restart: always

  app:
    image: nabo.codimd.dev/hackmdio/hackmd:2.4.1
    container_name: codimd_container
    environment:
      - CMD_DOMAIN=pad.fsi.uni-tuebingen.de
      - CMD_USECDN=false
      - CMD_PROTOCOL_USESSL=true
      - CMD_DB_URL=${CMD_DB_URL}
      - CMD_LDAP_URL=ldaps://ldap.fsi.uni-tuebingen.de
      - CMD_LDAP_SEARCHBASE=dc=fsi,dc=uni-tuebingen,dc=de
      - CMD_LDAP_SEARCHFILTER=(&(|(objectclass=posixAccount))(uid={{username}})(!(loginShell=/usr/sbin/nologin)))
      - CMD_LDAP_USERFIELDID=uid
      - CMD_LDAP_USERNAMEFIELD=cn
      - CMD_LDAP_TLS_CA=/etc/ssl/certs/ISRG_Root_X1.pem
      - CMD_EMAIL=false
      - CMD_ALLOW_GRAVATAR=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_ALLOW_FREEURL=true
      - CMD_DEFAULT_PERMISSION=limited
      - CMD_ALLOW_PDF_EXPORT=true
      - CMD_SESSION_LIFE=2592000000
    volumes:
      - ./config.json:/home/hackmd/app/config.json
      - /srv/data/codimd/persistuploads:/home/hackmd/app/public/uploads
    networks:
      backend:
        ipv4_address: 10.0.2.3
    restart: always
    depends_on:
      - database

  nginx:
    image: fsinf/nginx:latest
    container_name: codimd_nginx
    ports:
      - "134.2.220.61:8010:443"
    volumes:
      - /srv/docker-certificates/pad.fsi.uni-tuebingen.de/:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-codimd.conf:/etc/nginx/sites-enabled/nginx-codimd.conf:ro
      - /srv/docker/shared/nginx/ssl.conf:/etc/nginx/shared/ssl.conf:ro
      - /srv/docker/shared/nginx/security-headers.conf:/etc/nginx/shared/security-headers.conf:ro
    networks:
      backend:
        ipv4_address: 10.0.2.2
    restart: always

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.2.0/24
